title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

  nav:
  -title: Sistemas Informaticos
  -path: Sisinfo.md

  -title: Programación
  -path: Pro.md

  -title: Lenguaje de marcas
  -path: Lenmarc.md

  -title: Entornos de desarrollo
  -path: Entdes.md

  -title: Base de datos
  -path: Bd.md

  -title: Ingles
  -path: Ing.md
